#!/bin/bash
# -------------------------------------------
# AppRun for QuadCast 2 Control AppImage
# -------------------------------------------
HERE="$(dirname "$(readlink -f "${0}")")"
#PythonPath
export PYTHONPATH="$HERE/usr/lib/python3.11/site-packages:$PYTHONPATH"

exec python3 "$HERE/quadcast2.py" "$@"
#:3
